#!/usr/bin/env python3
"""Builds, publishes and stages the Quran media packs.

The recitations and mushaf page scans never go into git or the base app. They are
grouped into packs: Google Play serves the packs through Play Asset Delivery, and the
quran-cdn Worker serves the same packs from R2 to installs that did not come from Play.

    layout   (once, or whenever the media changes) hash the media, group surahs into
             packs, build one deterministic zip per pack and write the committed layout:
             android-app/quran-assets/manifest.tsv, the app asset quran/packs.json and one
             android-app/quran-packs/<pack>/build.gradle.kts per pack.
    publish  upload the zips that the CDN does not serve yet (needs wrangler + API token).
    stage    put every pack's files in android-app/quran-packs/<pack>/src/main/assets so
             bundleRelease can package them; downloads from the CDN unless --from-dir.
    check    confirm local folders hold exactly the bytes the layout describes.
    fetch-origin  download the original recordings listed in the manifest.

Only the standard library is used, so this runs the same way on Windows, macOS and CI.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

REPO = Path(__file__).resolve().parent.parent
ANDROID = REPO / 'android-app'
BASE_ASSETS = ANDROID / 'app' / 'src' / 'main' / 'assets'
TIMINGS_DIR = BASE_ASSETS / 'quran' / 'audio'
PAGES_JSON = BASE_ASSETS / 'quran' / 'pages' / 'pages.json'
LAYOUT_JSON = BASE_ASSETS / 'quran' / 'packs.json'
MANIFEST = ANDROID / 'quran-assets' / 'manifest.tsv'
BUILD = ANDROID / 'quran-assets' / 'build'
PACKS_ROOT = ANDROID / 'quran-packs'
WORKER_DIR = REPO / 'quran-cdn'
DEFAULT_CACHE = Path.home() / '.cache' / 'quran-assets'

MB = 1_000_000
TARGET_PACK_BYTES = 30 * MB
# Play asks for consent before downloading more than 200 MB over mobile data.
MAX_PACK_BYTES = 200 * MB
# A bundle holds at most 100 asset packs; one of them is the pages pack.
MAX_AUDIO_PACKS = 99
PAGES_PACK = 'quran_pages'
ARCHIVE_PREFIX = 'v1/packs/'
# Where each reciter's recordings were originally published, for provenance and fetch-origin.
ORIGINS = {'hosary': 'https://cdn.mp3quran.net/audio/mahmoud-husary/r5/{name}'}
GENERATED_BUILD_FILE = (
    '// Generated by scripts/quran_assets.py layout: one Play Asset Delivery pack.\n'
    'plugins { id("tunisianprayertimes.quran-asset-pack") }\n'
)
# Every zip entry gets the same timestamp and mode so equal files give equal archives.
ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)


class LayoutError(Exception):
    pass


@dataclass(frozen=True)
class Asset:
    pack: str
    path: str  # asset path inside the pack, e.g. quran/audio/hosary/001.mp3
    bytes: int
    sha256: str
    origin: str = '-'


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1 << 20), b''):
            digest.update(block)
    return digest.hexdigest()


def group_surahs(sizes: list[int], target: int = TARGET_PACK_BYTES, limit: int = MAX_PACK_BYTES) -> list[list[int]]:
    """Consecutive surah numbers per pack, starting a new pack once [target] would be exceeded."""
    packs: list[list[int]] = []
    current: list[int] = []
    total = 0
    for number, size in enumerate(sizes, start=1):
        if size >= limit:
            raise LayoutError(f'Surah {number} alone is {size / MB:.0f} MB, over the {limit / MB:.0f} MB pack limit')
        if current and total + size > target:
            packs.append(current)
            current, total = [], 0
        current.append(number)
        total += size
    if current:
        packs.append(current)
    return packs


def safe_member(name: str) -> str:
    """Rejects archive member names that could escape the extraction folder."""
    path = PurePosixPath(name)
    if not name or name.startswith('/') or '\\' in name or path.is_absolute() or '..' in path.parts or ':' in name:
        raise LayoutError(f'Unsafe archive entry: {name!r}')
    return str(path)


def build_archive(files: list[tuple[str, Path]], out: Path) -> str:
    """Writes a stored (uncompressed) zip with sorted entries and fixed metadata; returns its sha256."""
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(out.suffix + '.tmp')
    with zipfile.ZipFile(temporary, 'w', compression=zipfile.ZIP_STORED, allowZip64=True) as archive:
        for name, source in sorted(files):
            info = zipfile.ZipInfo(safe_member(name), date_time=ZIP_EPOCH)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            info.file_size = source.stat().st_size
            with source.open('rb') as src, archive.open(info, 'w') as dst:
                shutil.copyfileobj(src, dst, 1 << 20)
    temporary.replace(out)
    return sha256_of(out)


def extract_archive(archive: Path, destination: Path, expected: dict[str, int]) -> None:
    """Extracts exactly the [expected] files (path -> size) into [destination], replacing it."""
    staging = destination.with_name(destination.name + '.tmp')
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    with zipfile.ZipFile(archive) as zipped:
        names = [safe_member(info.filename) for info in zipped.infolist()]
        if sorted(names) != sorted(expected):
            raise LayoutError(f'{archive.name} does not hold the files the layout lists')
        for info in zipped.infolist():
            if info.file_size != expected[info.filename]:
                raise LayoutError(f'{info.filename} in {archive.name} has the wrong size')
            target = staging / info.filename
            target.parent.mkdir(parents=True, exist_ok=True)
            with zipped.open(info) as src, target.open('wb') as dst:
                shutil.copyfileobj(src, dst, 1 << 20)
    if destination.exists():
        shutil.rmtree(destination)
    staging.replace(destination)


# ── Committed layout ──────────────────────────────────────────────────────────

def read_manifest(path: Path | None = None) -> list[Asset]:
    path = path or MANIFEST
    if not path.exists():
        raise LayoutError(f'{path.relative_to(REPO)} is missing; run layout first')
    rows = []
    for line in path.read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#') or line.startswith('pack\t'):
            continue
        pack, asset_path, size, digest, origin = line.split('\t')
        rows.append(Asset(pack, asset_path, int(size), digest, origin))
    return rows


def write_manifest(assets: list[Asset], path: Path | None = None) -> None:
    path = path or MANIFEST
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ['# Quran media packs. Generated by scripts/quran_assets.py layout; do not edit by hand.',
             'pack\tpath\tbytes\tsha256\torigin']
    lines += [f'{a.pack}\t{a.path}\t{a.bytes}\t{a.sha256}\t{a.origin}' for a in assets]
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def read_layout(path: Path | None = None) -> dict:
    path = path or LAYOUT_JSON
    if not path.exists():
        raise LayoutError(f'{path.relative_to(REPO)} is missing; run layout first')
    return json.loads(path.read_text(encoding='utf-8'))


def archive_url(layout: dict, pack: dict) -> str:
    return layout['cdn'].rstrip('/') + '/' + pack['archive']['key']


def recitations() -> list[dict]:
    """Each reciter's timings.json: reciterId and the asset path of every surah."""
    found = []
    for timings in sorted(TIMINGS_DIR.glob('*/timings.json')):
        data = json.loads(timings.read_text(encoding='utf-8'))
        paths = [surah['assetPath'] for surah in sorted(data['surahs'], key=lambda s: s['number'])]
        if len(paths) != 114:
            raise LayoutError(f'{timings} lists {len(paths)} surahs, not 114')
        found.append({'reciterId': data['reciterId'], 'folder': timings.parent.name, 'paths': paths})
    if not found:
        raise LayoutError(f'No timings.json under {TIMINGS_DIR.relative_to(REPO)}; commit it first')
    return found


def page_paths() -> list[str]:
    if not PAGES_JSON.exists():
        raise LayoutError(f'{PAGES_JSON.relative_to(REPO)} is missing; commit it first')
    pages = json.loads(PAGES_JSON.read_text(encoding='utf-8'))['pages']
    return [f"quran/pages/{page['file']}" for page in pages]


class LocalFiles:
    """Finds media by file name in folders and zip files (zips are extracted to a temp folder)."""

    def __init__(self, sources: list[Path]):
        self.by_name: dict[str, Path] = {}
        self.temp = tempfile.TemporaryDirectory(prefix='quran-assets-')
        for source in sources:
            if source.is_file() and source.suffix.lower() == '.zip':
                folder = Path(self.temp.name) / source.stem
                with zipfile.ZipFile(source) as zipped:
                    for info in zipped.infolist():
                        if info.is_dir():
                            continue
                        target = folder / safe_member(info.filename)
                        target.parent.mkdir(parents=True, exist_ok=True)
                        with zipped.open(info) as src, target.open('wb') as dst:
                            shutil.copyfileobj(src, dst, 1 << 20)
                source = folder
            if not source.is_dir():
                raise LayoutError(f'{source} is neither a folder nor a zip file')
            for file in source.rglob('*'):
                if file.is_file():
                    self.by_name.setdefault(file.name, file)

    def find(self, asset_path: str) -> Path:
        name = PurePosixPath(asset_path).name
        if name not in self.by_name:
            raise LayoutError(f'No local file named {name} (for {asset_path})')
        return self.by_name[name]

    def close(self) -> None:
        self.temp.cleanup()


# ── Commands ──────────────────────────────────────────────────────────────────

def command_layout(args: argparse.Namespace) -> None:
    files = LocalFiles([Path(p) for p in args.from_dir])
    try:
        assets: list[Asset] = []
        packs: list[dict] = []
        sources: dict[str, Path] = {}

        def add_pack(name: str, kind: str, paths: list[str], extra: dict, origin_of) -> None:
            entries = []
            for asset_path in paths:
                source = files.find(asset_path)
                sources[asset_path] = source
                size = source.stat().st_size
                assets.append(Asset(name, asset_path, size, sha256_of(source), origin_of(asset_path)))
                entries.append({'path': asset_path, 'bytes': size})
            packs.append({'name': name, 'kind': kind, **extra, 'bytes': sum(e['bytes'] for e in entries), 'files': entries})

        pages = page_paths()
        add_pack(PAGES_PACK, 'pages', pages, {}, lambda _: '-')
        for recitation in recitations():
            folder = recitation['folder']
            pattern = ORIGINS.get(folder)
            sizes = [files.find(p).stat().st_size for p in recitation['paths']]
            groups = group_surahs(sizes, int(args.target_mb * MB))
            if len(groups) > MAX_AUDIO_PACKS:
                raise LayoutError(f'{len(groups)} packs for {folder}; raise --target-mb')
            for index, surahs in enumerate(groups, start=1):
                add_pack(f'quran_{folder}_{index:02d}', 'audio',
                         [recitation['paths'][n - 1] for n in surahs],
                         {'reciterId': recitation['reciterId'], 'surahs': [surahs[0], surahs[-1]]},
                         lambda p: pattern.format(name=PurePosixPath(p).name) if pattern else '-')
        if len(packs) > MAX_AUDIO_PACKS + 1:
            raise LayoutError(f'{len(packs)} packs exceed the 100-pack limit of an app bundle')

        BUILD.mkdir(parents=True, exist_ok=True)
        for pack in packs:
            if pack['bytes'] >= MAX_PACK_BYTES:
                print(f"! {pack['name']} is {pack['bytes'] / MB:.0f} MB: Play asks before using mobile data", file=sys.stderr)
            archive = BUILD / f"{pack['name']}.zip"
            digest = build_archive([(e['path'], sources[e['path']]) for e in pack['files']], archive)
            key = f"{ARCHIVE_PREFIX}{pack['name']}-{digest[:12]}.zip"
            final = BUILD / PurePosixPath(key).name
            archive.replace(final)
            pack['archive'] = {'key': key, 'bytes': final.stat().st_size, 'sha256': digest}
            print(f"  {pack['name']}: {len(pack['files'])} files, {pack['bytes'] / MB:.1f} MB")

        layout = {'version': 1, 'cdn': args.cdn.rstrip('/') + '/', 'packs': packs}
        LAYOUT_JSON.write_text(json.dumps(layout, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
        write_manifest(assets)
        write_pack_modules([p['name'] for p in packs])
        print(f'✓ {len(packs)} packs, {sum(a.bytes for a in assets) / MB:.0f} MB. Archives in {BUILD.relative_to(REPO)}')
    finally:
        files.close()


def write_pack_modules(names: list[str]) -> None:
    PACKS_ROOT.mkdir(parents=True, exist_ok=True)
    for stale in PACKS_ROOT.iterdir():
        build_file = stale / 'build.gradle.kts'
        if stale.is_dir() and stale.name not in names and build_file.exists() \
                and build_file.read_text(encoding='utf-8') == GENERATED_BUILD_FILE:
            shutil.rmtree(stale)
    for name in names:
        (PACKS_ROOT / name).mkdir(exist_ok=True)
        (PACKS_ROOT / name / 'build.gradle.kts').write_text(GENERATED_BUILD_FILE, encoding='utf-8')


def served_size(url: str) -> int | None:
    request = urllib.request.Request(url, method='HEAD')
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return int(response.headers.get('Content-Length', '-1'))
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise


def command_publish(args: argparse.Namespace) -> None:
    layout = read_layout()
    wrangler = shutil.which('npx')
    if wrangler is None:
        raise LayoutError('npx (Node.js) is needed to run wrangler')
    for pack in layout['packs']:
        archive = pack['archive']
        url = archive_url(layout, pack)
        if not args.force and served_size(url) == archive['bytes']:
            print(f"  {pack['name']}: already published")
            continue
        local = BUILD / PurePosixPath(archive['key']).name
        if not local.exists() or sha256_of(local) != archive['sha256']:
            raise LayoutError(f'{local.relative_to(REPO)} is missing or stale; run layout with the same media')
        print(f"  {pack['name']}: uploading {archive['bytes'] / MB:.1f} MB")
        subprocess.run([wrangler, 'wrangler', 'r2', 'object', 'put', f"{args.bucket}/{archive['key']}",
                        '--file', str(local), '--content-type', 'application/zip', '--remote'],
                       cwd=WORKER_DIR, check=True)
    print('✓ Every pack is published')


def download(url: str, target: Path) -> None:
    """Downloads to target, resuming a previous partial download when the server allows it."""
    partial = target.with_suffix(target.suffix + '.part')
    offset = partial.stat().st_size if partial.exists() else 0
    request = urllib.request.Request(url, headers={'Range': f'bytes={offset}-'} if offset else {})
    try:
        response = urllib.request.urlopen(request, timeout=120)
    except urllib.error.HTTPError as error:
        if offset and error.code == 416:  # The partial file is already complete or too long.
            partial.unlink()
            return download(url, target)
        raise
    with response:
        resumed = response.status == 206 and response.headers.get('Content-Range', '').startswith(f'bytes {offset}-')
        if offset and not resumed and response.status != 200:
            partial.unlink()
            return download(url, target)
        with partial.open('ab' if offset and resumed else 'wb') as out:
            shutil.copyfileobj(response, out, 1 << 20)
    partial.replace(target)


def cached_archive(layout: dict, pack: dict, cache: Path) -> Path:
    archive = pack['archive']
    path = cache / PurePosixPath(archive['key']).name
    for attempt in range(2):
        if path.exists() and path.stat().st_size == archive['bytes'] and sha256_of(path) == archive['sha256']:
            return path
        if path.exists():
            path.unlink()
        if attempt == 0:
            print(f"  {pack['name']}: downloading {archive['bytes'] / MB:.1f} MB")
            cache.mkdir(parents=True, exist_ok=True)
            download(archive_url(layout, pack), path)
    raise LayoutError(f"{pack['name']}: the downloaded archive does not match packs.json")


def staged_dir(pack: str) -> Path:
    return PACKS_ROOT / pack / 'src' / 'main' / 'assets'


def stamp_of(pack: str) -> Path:
    return PACKS_ROOT / pack / 'src' / '.staged'


def is_staged(pack: dict) -> bool:
    stamp = stamp_of(pack['name'])
    if not stamp.exists() or stamp.read_text().strip() != pack['archive']['sha256']:
        return False
    root = staged_dir(pack['name'])
    return all((root / f['path']).is_file() and (root / f['path']).stat().st_size == f['bytes'] for f in pack['files'])


def command_stage(args: argparse.Namespace) -> None:
    layout = read_layout()
    wanted = set(args.packs or [])
    manifest = {a.path: a for a in read_manifest()}
    files = LocalFiles([Path(p) for p in args.from_dir]) if args.from_dir else None
    try:
        for pack in layout['packs']:
            if wanted and pack['name'] not in wanted:
                continue
            if is_staged(pack):
                continue
            expected = {f['path']: f['bytes'] for f in pack['files']}
            root = staged_dir(pack['name'])
            if files:
                staging = root.with_name(root.name + '.tmp')
                if staging.exists():
                    shutil.rmtree(staging)
                for asset_path in expected:
                    source = files.find(asset_path)
                    if sha256_of(source) != manifest[asset_path].sha256:
                        raise LayoutError(f'{source} differs from the layout ({asset_path})')
                    target = staging / asset_path
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(source, target)
                if root.exists():
                    shutil.rmtree(root)
                staging.replace(root)
            else:
                cache = Path(args.cache)
                archive = cached_archive(layout, pack, cache)
                extract_archive(archive, root, expected)
                if args.no_cache:
                    archive.unlink()
            stamp_of(pack['name']).write_text(pack['archive']['sha256'] + '\n')
            print(f"  {pack['name']}: staged")
    finally:
        if files:
            files.close()
    print('✓ Every pack is staged for bundleRelease')


def command_check(args: argparse.Namespace) -> None:
    files = LocalFiles([Path(p) for p in args.from_dir])
    try:
        problems = 0
        for asset in read_manifest():
            try:
                source = files.find(asset.path)
            except LayoutError as missing:
                if not args.only_present:
                    print(f'✗ {missing}')
                    problems += 1
                continue
            if source.stat().st_size != asset.bytes or sha256_of(source) != asset.sha256:
                print(f'✗ {source} differs from {asset.path}')
                problems += 1
        if problems:
            raise LayoutError(f'{problems} problems')
        print('✓ The local files match the layout byte for byte')
    finally:
        files.close()


def command_fetch_origin(args: argparse.Namespace) -> None:
    target = Path(args.to)
    target.mkdir(parents=True, exist_ok=True)
    for asset in read_manifest():
        if asset.origin == '-':
            continue
        path = target / PurePosixPath(asset.path).name
        if path.exists() and path.stat().st_size == asset.bytes and sha256_of(path) == asset.sha256:
            continue
        print(f'  {path.name}')
        download(asset.origin, path)
        if sha256_of(path) != asset.sha256:
            raise LayoutError(f'{asset.origin} no longer serves the bytes in the layout')
    print(f'✓ Originals in {target}')


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest='command', required=True)

    layout = commands.add_parser('layout', help='hash media, group packs, build zips, write the layout')
    layout.add_argument('--from-dir', action='append', required=True,
                        help='folder or zip holding the MP3s or page scans (repeatable)')
    layout.add_argument('--cdn', required=True, help='base URL of the quran-cdn Worker')
    layout.add_argument('--target-mb', type=float, default=TARGET_PACK_BYTES / MB)
    layout.set_defaults(run=command_layout)

    publish = commands.add_parser('publish', help='upload pack zips the CDN does not serve yet')
    publish.add_argument('--bucket', default='tunisian-quran-assets')
    publish.add_argument('--force', action='store_true', help='upload even if the CDN already serves the key')
    publish.set_defaults(run=command_publish)

    stage = commands.add_parser('stage', help='put pack files where bundleRelease packages them')
    stage.add_argument('--cache', default=str(DEFAULT_CACHE))
    stage.add_argument('--no-cache', action='store_true', help='delete each archive after extracting it')
    stage.add_argument('--from-dir', action='append', help='use local folders or zips instead of the CDN')
    stage.add_argument('--packs', nargs='*', help='only these packs')
    stage.set_defaults(run=command_stage)

    check = commands.add_parser('check', help='compare local media with the layout')
    check.add_argument('--from-dir', action='append', required=True)
    check.add_argument('--only-present', action='store_true', help='ignore layout files the folders lack')
    check.set_defaults(run=command_check)

    fetch = commands.add_parser('fetch-origin', help='download the original recordings in the manifest')
    fetch.add_argument('--to', required=True)
    fetch.set_defaults(run=command_fetch_origin)

    args = parser.parse_args(argv)
    try:
        args.run(args)
    except (LayoutError, urllib.error.URLError, subprocess.CalledProcessError) as error:
        print(f'✗ {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
