#!/usr/bin/env python3
"""Builds, publishes and stages the Quran media packs.

The recitations and mushaf page scans never go into git or the base app. They are
grouped into packs, which the quran-cdn Worker serves from R2. Google Play also serves the
page scans and the first ten reciters' packs through Play Asset Delivery to Play installs;
later reciters come from the Worker on every install.

    convert  re-encode recordings as 64 kbps mono MP3 at a constant bitrate (needs ffmpeg).
    layout   (once, or whenever the media changes) hash the media, group surahs into
             packs, build one deterministic zip per pack and write the committed layout:
             android-app/quran-assets/manifest.tsv, the app asset quran/packs.json and one
             android-app/quran-packs/<pack>/build.gradle.kts per Play pack.
    publish  upload the zips that the CDN does not serve yet (needs CLOUDFLARE_API_TOKEN and
             CLOUDFLARE_ACCOUNT_ID; the token needs Workers R2 Storage: Edit).
    stage    put every Play pack's files in android-app/quran-packs/<pack>/src/main/assets so
             bundleRelease can package them; downloads from the CDN unless --from-dir.
    check    confirm local folders hold exactly the bytes the layout describes.
    fetch-origin  download the recordings the recitations were converted from.

Only the standard library is used, so this runs the same way on Windows, macOS and CI;
convert alone also needs ffmpeg.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import http.client
import json
import os
import re
import shutil
import socket
import subprocess
import time
import sys
import tempfile
import urllib.error
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

REPO = Path(__file__).resolve().parent.parent
ANDROID = REPO / 'android-app'
BASE_ASSETS = ANDROID / 'app' / 'src' / 'main' / 'assets'
TIMINGS_DIR = BASE_ASSETS / 'quran' / 'audio'
PAGES_JSON = BASE_ASSETS / 'quran' / 'pages' / 'pages.json'
LAYOUT_JSON = BASE_ASSETS / 'quran' / 'packs.json'
MANIFEST = ANDROID / 'quran-assets' / 'manifest.tsv'
BUILD = ANDROID / 'quran-assets' / 'build'
PACKS_ROOT = ANDROID / 'quran-packs'
CLOUDFLARE_API = 'https://api.cloudflare.com/client/v4'
# The R2 API takes uploads of up to 300 MiB in one request.
MAX_UPLOAD_BYTES = 300 * 1024 * 1024
DEFAULT_CACHE = Path.home() / '.cache' / 'quran-assets'

MB = 1_000_000
# Packs of reciters only the Worker serves: small, so starting a surah downloads little.
TARGET_PACK_BYTES = 30 * MB
# Play asks for consent before downloading more than 200 MB over mobile data.
MAX_PACK_BYTES = 200 * MB
# A bundle holds at most 100 asset packs: the pages pack, then 9 per Play reciter for the first
# 10 reciters. Later reciters are served by the Worker alone, on Play installs too.
MAX_PLAY_PACKS = 100
PLAY_RECITERS = 10
PLAY_PACKS_PER_RECITER = 9
PLAY, CDN = 'play', 'cdn'
# Half the size of mp3quran's 128 kbps stereo files with no audible loss on these old tape
# recordings, and constant: Android seeks to a verse exactly only in constant-bitrate MP3.
AUDIO_KBPS = 64
PACK_NAME = re.compile(r'[a-z][a-z0-9_]*')
PAGES_PACK = 'quran_pages'
ARCHIVE_PREFIX = 'v1/packs/'
DOWNLOAD_TRIES = 5
# Where each reciter's recordings were originally published, for provenance and fetch-origin.
ORIGINS = {'hosary': 'https://cdn.mp3quran.net/audio/mahmoud-husary/r5/{name}'}
GENERATED_BUILD_FILE = (
    '// Generated by scripts/quran_assets.py layout: one Play Asset Delivery pack.\n'
    'plugins { id("tunisianprayertimes.quran-asset-pack") }\n'
)
# Every zip entry gets the same timestamp and mode so equal files give equal archives.
ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)
# Cloudflare answers 403 to urllib's default "Python-urllib/3.x" user agent.
USER_AGENT = 'TunisianPrayerTimes-quran-assets/1 (+https://github.com/bsafwen/TunisianPrayerTimes)'


class LayoutError(Exception):
    pass


@dataclass(frozen=True)
class Asset:
    pack: str
    path: str  # asset path inside the pack, e.g. quran/audio/hosary/001.mp3
    bytes: int
    sha256: str
    origin: str = '-'
    delivery: str = PLAY


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1 << 20), b''):
            digest.update(block)
    return digest.hexdigest()


def group_surahs(sizes: list[int], target: int = TARGET_PACK_BYTES, limit: int = MAX_PACK_BYTES) -> list[list[int]]:
    """Consecutive surah numbers per pack, starting a new pack once [target] would be exceeded."""
    packs: list[list[int]] = []
    current: list[int] = []
    total = 0
    for number, size in enumerate(sizes, start=1):
        if size >= limit:
            raise LayoutError(f'Surah {number} alone is {size / MB:.0f} MB, over the {limit / MB:.0f} MB pack limit')
        if current and total + size > target:
            packs.append(current)
            current, total = [], 0
        current.append(number)
        total += size
    if current:
        packs.append(current)
    return packs


def split_surahs(sizes: list[int], count: int, limit: int = MAX_PACK_BYTES) -> list[list[int]]:
    """At most [count] packs of consecutive surahs, as even as can be: the largest is as small as possible."""
    low, high = max(sizes), sum(sizes)
    while low < high:
        middle = (low + high) // 2
        if len(group_surahs(sizes, middle, limit)) <= count:
            high = middle
        else:
            low = middle + 1
    return group_surahs(sizes, low, limit)


def assign_deliveries(reciters: list[str], previous: dict[str, str]) -> dict[str, str]:
    """Google Play for the first PLAY_RECITERS reciters laid out, the Worker for the rest.

    Reciters new to this layout fill the free Play places in [reciters] order (their folder names).

    A reciter keeps what an earlier layout gave it: moving one would rename its packs and make
    everyone who downloaded it download it again.
    """
    kept = {reciter: previous[reciter] for reciter in reciters if reciter in previous}
    free = PLAY_RECITERS - list(kept.values()).count(PLAY)
    deliveries = {}
    for reciter in reciters:
        if reciter in kept:
            deliveries[reciter] = kept[reciter]
        elif free > 0:
            deliveries[reciter] = PLAY
            free -= 1
        else:
            deliveries[reciter] = CDN
    return deliveries


MPEG1_LAYER3_KBPS = (0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320)


def mp3_format(path: Path) -> tuple[int, bool, bool] | None:
    """(kbps, mono, constant bitrate) from an MPEG-1 Layer III file's first frame; None for anything else."""
    with path.open('rb') as stream:
        tag = stream.read(10)
        if len(tag) == 10 and tag[:3] == b'ID3':
            size = (tag[6] & 0x7f) << 21 | (tag[7] & 0x7f) << 14 | (tag[8] & 0x7f) << 7 | tag[9] & 0x7f
            stream.seek(10 + size + (10 if tag[5] & 0x10 else 0))
        else:
            stream.seek(0)
        data = stream.read(8192)
    for i in range(len(data) - 3):
        # Frame sync of any MPEG audio frame; the first one must be MPEG-1 Layer III, then a valid bitrate and
        # sample rate. Scanning on past an MPEG-2 frame would find look-alike headers in its audio data.
        if data[i] != 0xFF or data[i + 1] & 0xE0 != 0xE0:
            continue
        if data[i + 1] & 0xFE != 0xFA:
            return None
        bitrate, rate = data[i + 2] >> 4, (data[i + 2] >> 2) & 3
        if not 0 < bitrate < 15 or rate == 3:
            continue
        # Encoders announce a variable bitrate in a Xing or VBRI header inside the first frame.
        first_frame = data[i:i + 200]
        return MPEG1_LAYER3_KBPS[bitrate], data[i + 3] >> 6 == 3, b'Xing' not in first_frame and b'VBRI' not in first_frame
    return None


def is_recitation_format(path: Path) -> bool:
    return mp3_format(path) == (AUDIO_KBPS, True, True)


def check_recitation_format(path: Path) -> None:
    if is_recitation_format(path):
        return
    found = mp3_format(path)
    described = 'not an MPEG-1 Layer III file' if found is None else \
        f"{found[0]} kbps {'mono' if found[1] else 'stereo'}{'' if found[2] else ' at a variable bitrate'}"
    raise LayoutError(f'{path} is {described}; recitations are {AUDIO_KBPS} kbps mono at a constant bitrate. '
                      f'Convert them first: quran_assets.py convert --from-dir <originals> --to <folder>')


def safe_member(name: str) -> str:
    """Rejects archive member names that could escape the extraction folder."""
    path = PurePosixPath(name)
    if not name or name.startswith('/') or '\\' in name or path.is_absolute() or '..' in path.parts or ':' in name:
        raise LayoutError(f'Unsafe archive entry: {name!r}')
    return str(path)


def build_archive(files: list[tuple[str, Path]], out: Path) -> str:
    """Writes a stored (uncompressed) zip with sorted entries and fixed metadata; returns its sha256."""
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(out.suffix + '.tmp')
    with zipfile.ZipFile(temporary, 'w', compression=zipfile.ZIP_STORED, allowZip64=True) as archive:
        for name, source in sorted(files):
            info = zipfile.ZipInfo(safe_member(name), date_time=ZIP_EPOCH)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            info.file_size = source.stat().st_size
            with source.open('rb') as src, archive.open(info, 'w') as dst:
                shutil.copyfileobj(src, dst, 1 << 20)
    temporary.replace(out)
    return sha256_of(out)


def extract_archive(archive: Path, destination: Path, expected: dict[str, int]) -> None:
    """Extracts exactly the [expected] files (path -> size) into [destination], replacing it."""
    staging = destination.with_name(destination.name + '.tmp')
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True)
    with zipfile.ZipFile(archive) as zipped:
        names = [safe_member(info.filename) for info in zipped.infolist()]
        if sorted(names) != sorted(expected):
            raise LayoutError(f'{archive.name} does not hold the files the layout lists')
        for info in zipped.infolist():
            if info.file_size != expected[info.filename]:
                raise LayoutError(f'{info.filename} in {archive.name} has the wrong size')
            target = staging / info.filename
            target.parent.mkdir(parents=True, exist_ok=True)
            with zipped.open(info) as src, target.open('wb') as dst:
                shutil.copyfileobj(src, dst, 1 << 20)
    if destination.exists():
        shutil.rmtree(destination)
    staging.replace(destination)


# ── Committed layout ──────────────────────────────────────────────────────────

def read_manifest(path: Path | None = None) -> list[Asset]:
    path = path or MANIFEST
    if not path.exists():
        raise LayoutError(f'{path.relative_to(REPO)} is missing; run layout first')
    rows = []
    for line in path.read_text(encoding='utf-8').splitlines():
        if not line or line.startswith('#') or line.startswith('pack\t'):
            continue
        pack, asset_path, size, digest, origin, *delivery = line.split('\t')
        rows.append(Asset(pack, asset_path, int(size), digest, origin, *delivery))
    return rows


def write_manifest(assets: list[Asset], path: Path | None = None) -> None:
    path = path or MANIFEST
    path.parent.mkdir(parents=True, exist_ok=True)
    # origin: the recording a recitation was converted from. delivery: play packs are also
    # Play Asset Delivery modules; cdn packs come from the quran-cdn Worker alone.
    lines = ['# Quran media packs. Generated by scripts/quran_assets.py layout; do not edit by hand.',
             'pack\tpath\tbytes\tsha256\torigin\tdelivery']
    lines += [f'{a.pack}\t{a.path}\t{a.bytes}\t{a.sha256}\t{a.origin}\t{a.delivery}' for a in assets]
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def read_layout(path: Path | None = None) -> dict:
    path = path or LAYOUT_JSON
    if not path.exists():
        raise LayoutError(f'{path.relative_to(REPO)} is missing; run layout first')
    return json.loads(path.read_text(encoding='utf-8'))


def archive_url(layout: dict, pack: dict) -> str:
    return layout['cdn'].rstrip('/') + '/' + pack['archive']['key']


def delivery_of(pack: dict) -> str:
    return pack.get('delivery', PLAY)


def previous_deliveries() -> dict[str, str]:
    """Each reciter's delivery in the layout being replaced; empty for the first layout."""
    if not LAYOUT_JSON.exists():
        return {}
    return {pack['reciterId']: delivery_of(pack) for pack in read_layout()['packs'] if pack['kind'] == 'audio'}


def recitations() -> list[dict]:
    """Each reciter's timings.json: reciterId and the asset path of every surah."""
    found = []
    for timings in sorted(TIMINGS_DIR.glob('*/timings.json')):
        data = json.loads(timings.read_text(encoding='utf-8'))
        paths = [surah['assetPath'] for surah in sorted(data['surahs'], key=lambda s: s['number'])]
        if len(paths) != 114:
            raise LayoutError(f'{timings} lists {len(paths)} surahs, not 114')
        found.append({'reciterId': data['reciterId'], 'folder': timings.parent.name, 'paths': paths})
    if not found:
        raise LayoutError(f'No timings.json under {TIMINGS_DIR.relative_to(REPO)}; commit it first')
    return found


def page_paths() -> list[str]:
    if not PAGES_JSON.exists():
        raise LayoutError(f'{PAGES_JSON.relative_to(REPO)} is missing; commit it first')
    pages = json.loads(PAGES_JSON.read_text(encoding='utf-8'))['pages']
    return [f"quran/pages/{page['file']}" for page in pages]


class LocalFiles:
    """Finds media by file name in folders and zip files (zips are extracted to a temp folder).

    Reciters share file names (001.mp3 …): when several files have the name, the one in a folder
    named like the asset's (quran/audio/hosary/001.mp3 → …/hosary/001.mp3) is used.
    """

    def __init__(self, sources: list[Path]):
        self.by_name: dict[str, list[Path]] = {}
        self.temp = tempfile.TemporaryDirectory(prefix='quran-assets-')
        for source in sources:
            if source.is_file() and source.suffix.lower() == '.zip':
                folder = Path(self.temp.name) / source.stem
                with zipfile.ZipFile(source) as zipped:
                    for info in zipped.infolist():
                        if info.is_dir():
                            continue
                        target = folder / safe_member(info.filename)
                        target.parent.mkdir(parents=True, exist_ok=True)
                        with zipped.open(info) as src, target.open('wb') as dst:
                            shutil.copyfileobj(src, dst, 1 << 20)
                source = folder
            if not source.is_dir():
                raise LayoutError(f'{source} is neither a folder nor a zip file')
            for file in source.rglob('*'):
                if file.is_file():
                    found = self.by_name.setdefault(file.name, [])
                    if all(file.resolve() != known.resolve() for known in found):
                        found.append(file)

    def find(self, asset_path: str) -> Path:
        path = PurePosixPath(asset_path)
        candidates = self.by_name.get(path.name, [])
        if not candidates:
            raise LayoutError(f'No local file named {path.name} (for {asset_path})')
        if len(candidates) == 1:
            return candidates[0]
        in_folder = [c for c in candidates if c.parent.name == path.parent.name]
        if len(in_folder) != 1:
            raise LayoutError(f'{len(candidates)} local files are named {path.name}: put each reciter\'s files '
                              f'in a folder named after it ({path.parent.name}/ for {asset_path})')
        return in_folder[0]

    def close(self) -> None:
        self.temp.cleanup()


# ── Commands ──────────────────────────────────────────────────────────────────

def command_layout(args: argparse.Namespace) -> None:
    files = LocalFiles([Path(p) for p in args.from_dir])
    try:
        assets: list[Asset] = []
        packs: list[dict] = []
        sources: dict[str, Path] = {}

        def add_pack(name: str, kind: str, paths: list[str], extra: dict, origin_of) -> None:
            entries = []
            for asset_path in paths:
                source = files.find(asset_path)
                sources[asset_path] = source
                size = source.stat().st_size
                assets.append(Asset(name, asset_path, size, sha256_of(source), origin_of(asset_path), extra['delivery']))
                entries.append({'path': asset_path, 'bytes': size})
            packs.append({'name': name, 'kind': kind, **extra, 'bytes': sum(e['bytes'] for e in entries), 'files': entries})

        pages = page_paths()
        add_pack(PAGES_PACK, 'pages', pages, {'delivery': PLAY}, lambda _: '-')
        found = recitations()
        deliveries = assign_deliveries([r['reciterId'] for r in found], previous_deliveries())
        for recitation in found:
            folder = recitation['folder']
            if not PACK_NAME.fullmatch(folder):
                raise LayoutError(f'Reciter folder {folder!r} must be lowercase letters, digits and underscores')
            delivery = deliveries[recitation['reciterId']]
            pattern = ORIGINS.get(folder)
            recordings = [files.find(p) for p in recitation['paths']]
            for recording in recordings:
                check_recitation_format(recording)
            sizes = [recording.stat().st_size for recording in recordings]
            if delivery == PLAY:
                groups = split_surahs(sizes, PLAY_PACKS_PER_RECITER)
            else:
                groups = group_surahs(sizes, int(args.target_mb * MB))
            for index, surahs in enumerate(groups, start=1):
                add_pack(f'quran_{folder}_{index:02d}', 'audio',
                         [recitation['paths'][n - 1] for n in surahs],
                         {'delivery': delivery, 'reciterId': recitation['reciterId'], 'surahs': [surahs[0], surahs[-1]]},
                         lambda p: pattern.format(name=PurePosixPath(p).name) if pattern else '-')
            print(f"  {recitation['reciterId']}: {'Google Play and the Worker' if delivery == PLAY else 'the Worker only'}, "
                  f"{len(groups)} pack{'' if len(groups) == 1 else 's'}, {sum(sizes) / MB:.0f} MB")
        play_packs = [p['name'] for p in packs if p['delivery'] == PLAY]
        if len(play_packs) > MAX_PLAY_PACKS:
            raise LayoutError(f'{len(play_packs)} Play packs exceed the {MAX_PLAY_PACKS}-pack limit of an app bundle')

        BUILD.mkdir(parents=True, exist_ok=True)
        for pack in packs:
            if pack['delivery'] == PLAY and pack['bytes'] >= MAX_PACK_BYTES:
                print(f"! {pack['name']} is {pack['bytes'] / MB:.0f} MB: Play asks before using mobile data", file=sys.stderr)
            archive = BUILD / f"{pack['name']}.zip"
            digest = build_archive([(e['path'], sources[e['path']]) for e in pack['files']], archive)
            key = f"{ARCHIVE_PREFIX}{pack['name']}-{digest[:12]}.zip"
            final = BUILD / PurePosixPath(key).name
            archive.replace(final)
            pack['archive'] = {'key': key, 'bytes': final.stat().st_size, 'sha256': digest}
            print(f"  {pack['name']}: {len(pack['files'])} files, {pack['bytes'] / MB:.1f} MB")

        layout = {'version': 1, 'cdn': args.cdn.rstrip('/') + '/', 'packs': packs}
        LAYOUT_JSON.write_text(json.dumps(layout, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
        write_manifest(assets)
        write_pack_modules(play_packs)
        print(f'✓ {len(packs)} packs, {sum(a.bytes for a in assets) / MB:.0f} MB. Archives in {BUILD.relative_to(REPO)}')
    finally:
        files.close()


def write_pack_modules(names: list[str]) -> None:
    PACKS_ROOT.mkdir(parents=True, exist_ok=True)
    for stale in PACKS_ROOT.iterdir():
        build_file = stale / 'build.gradle.kts'
        if stale.is_dir() and stale.name not in names and build_file.exists() \
                and build_file.read_text(encoding='utf-8') == GENERATED_BUILD_FILE:
            shutil.rmtree(stale)
    for name in names:
        (PACKS_ROOT / name).mkdir(exist_ok=True)
        (PACKS_ROOT / name / 'build.gradle.kts').write_text(GENERATED_BUILD_FILE, encoding='utf-8')


def served_size(url: str) -> int | None:
    request = urllib.request.Request(url, method='HEAD', headers={'User-Agent': USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return int(response.headers.get('Content-Length', '-1'))
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise


def upload(account: str, token: str, bucket: str, key: str, path: Path) -> None:
    """Uploads one archive through Cloudflare's R2 API, which needs nothing but Python."""
    size = path.stat().st_size
    if size > MAX_UPLOAD_BYTES:
        raise LayoutError(f'{path.name} is {size / MB:.0f} MB, over the R2 API upload limit; lower --target-mb')
    url = f'{CLOUDFLARE_API}/accounts/{account}/r2/buckets/{bucket}/objects/{key}'
    headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/zip',
               'Content-Length': str(size), 'User-Agent': USER_AGENT}
    with path.open('rb') as body:
        request = urllib.request.Request(url, data=body, method='PUT', headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=300) as response:
                result = json.load(response)
        except urllib.error.HTTPError as error:
            try:
                result = json.load(error)
            except ValueError:
                result = {'errors': [f'HTTP {error.code}']}
    if not result.get('success'):
        raise LayoutError(f'Cloudflare refused {key}: {result.get("errors")}')


def command_publish(args: argparse.Namespace) -> None:
    layout = read_layout()
    account = os.environ.get('CLOUDFLARE_ACCOUNT_ID')
    token = os.environ.get('CLOUDFLARE_API_TOKEN')
    if not account or not token:
        raise LayoutError('Set CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN to publish')
    for pack in layout['packs']:
        archive = pack['archive']
        url = archive_url(layout, pack)
        if not args.force and served_size(url) == archive['bytes']:
            print(f"  {pack['name']}: already published")
            continue
        local = BUILD / PurePosixPath(archive['key']).name
        if not local.exists() or sha256_of(local) != archive['sha256']:
            raise LayoutError(f'{local.relative_to(REPO)} is missing or stale; run layout with the same media')
        print(f"  {pack['name']}: uploading {archive['bytes'] / MB:.1f} MB")
        upload(account, token, args.bucket, archive['key'], local)
        # The CDN must now serve exactly this archive.
        if served_size(url) != archive['bytes']:
            raise LayoutError(f"{url} does not serve the uploaded {pack['name']}")
    print('✓ Every pack is published')


class Incomplete(OSError):
    """The connection ended before the whole file arrived; the partial file is kept to resume."""


def download(url: str, target: Path, expected: int | None = None) -> None:
    """Downloads to target, resuming a previous partial download when the server allows it."""
    partial = target.with_suffix(target.suffix + '.part')
    offset = partial.stat().st_size if partial.exists() else 0
    headers = {'User-Agent': USER_AGENT, **({'Range': f'bytes={offset}-'} if offset else {})}
    request = urllib.request.Request(url, headers=headers)
    try:
        response = urllib.request.urlopen(request, timeout=120)
    except urllib.error.HTTPError as error:
        if offset and error.code == 416:  # The partial file is already complete or too long.
            partial.unlink()
            return download(url, target, expected)
        raise
    with response:
        resumed = response.status == 206 and response.headers.get('Content-Range', '').startswith(f'bytes {offset}-')
        if offset and not resumed and response.status != 200:
            partial.unlink()
            return download(url, target, expected)
        # The size the server says the whole file has: a changed or wrong file is a layout problem,
        # not a connection to resume.
        length = response.headers.get('Content-Length')
        total = response.headers.get('Content-Range', '').rpartition('/')[2] if resumed else length
        declared = int(total) if total and total.isdigit() else None
        if expected is not None and declared is not None and declared != expected:
            raise LayoutError(f'{url} serves {declared} bytes; the layout says {expected}')
        expected = expected if expected is not None else declared
        try:
            with partial.open('ab' if offset and resumed else 'wb') as out:
                shutil.copyfileobj(response, out, 1 << 20)
        # socket.timeout is not a TimeoutError before Python 3.10.
        except (http.client.IncompleteRead, ConnectionError, TimeoutError, socket.timeout) as error:
            raise Incomplete(f'{url}: transfer interrupted ({error})') from error
    if expected is not None and partial.stat().st_size < expected:
        raise Incomplete(f'{url}: connection closed after {partial.stat().st_size} of {expected} bytes')
    partial.replace(target)


def cached_archive(layout: dict, pack: dict, cache: Path) -> Path:
    archive = pack['archive']
    path = cache / PurePosixPath(archive['key']).name
    for attempt in range(2):
        if path.exists() and path.stat().st_size == archive['bytes'] and sha256_of(path) == archive['sha256']:
            return path
        if path.exists():
            path.unlink()
        if attempt == 0:
            print(f"  {pack['name']}: downloading {archive['bytes'] / MB:.1f} MB")
            cache.mkdir(parents=True, exist_ok=True)
            for tries in range(DOWNLOAD_TRIES):
                try:
                    download(archive_url(layout, pack), path, archive['bytes'])
                    break
                except Incomplete:  # Resume from what arrived.
                    if tries == DOWNLOAD_TRIES - 1:
                        raise
                except urllib.error.HTTPError as error:  # The CDN is busy: wait, then resume.
                    if error.code not in (429, 500, 502, 503, 504) or tries == DOWNLOAD_TRIES - 1:
                        raise
                    retry_after = error.headers.get('Retry-After', '')
                    time.sleep(min(int(retry_after), 60) if retry_after.isdigit() else 5)
    raise LayoutError(f"{pack['name']}: the downloaded archive does not match packs.json")


def staged_dir(pack: str) -> Path:
    return PACKS_ROOT / pack / 'src' / 'main' / 'assets'


def stamp_of(pack: str) -> Path:
    return PACKS_ROOT / pack / 'src' / '.staged'


def is_staged(pack: dict) -> bool:
    stamp = stamp_of(pack['name'])
    if not stamp.exists() or stamp.read_text().strip() != pack['archive']['sha256']:
        return False
    root = staged_dir(pack['name'])
    return all((root / f['path']).is_file() and (root / f['path']).stat().st_size == f['bytes'] for f in pack['files'])


def command_stage(args: argparse.Namespace) -> None:
    layout = read_layout()
    wanted = set(args.packs or [])
    manifest = {a.path: a for a in read_manifest()}
    files = LocalFiles([Path(p) for p in args.from_dir]) if args.from_dir else None
    try:
        # Only Play packs go into the bundle; the Worker alone serves the others.
        for pack in layout['packs']:
            if delivery_of(pack) != PLAY or wanted and pack['name'] not in wanted:
                continue
            if is_staged(pack):
                continue
            expected = {f['path']: f['bytes'] for f in pack['files']}
            root = staged_dir(pack['name'])
            if files:
                staging = root.with_name(root.name + '.tmp')
                if staging.exists():
                    shutil.rmtree(staging)
                for asset_path in expected:
                    source = files.find(asset_path)
                    if sha256_of(source) != manifest[asset_path].sha256:
                        raise LayoutError(f'{source} differs from the layout ({asset_path})')
                    target = staging / asset_path
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(source, target)
                if root.exists():
                    shutil.rmtree(root)
                staging.replace(root)
            else:
                cache = Path(args.cache)
                archive = cached_archive(layout, pack, cache)
                extract_archive(archive, root, expected)
                if args.no_cache:
                    archive.unlink()
            stamp_of(pack['name']).write_text(pack['archive']['sha256'] + '\n')
            print(f"  {pack['name']}: staged")
    finally:
        if files:
            files.close()
    print('✓ Every Play pack is staged for bundleRelease')


def command_check(args: argparse.Namespace) -> None:
    files = LocalFiles([Path(p) for p in args.from_dir])
    try:
        problems = 0
        for asset in read_manifest():
            try:
                source = files.find(asset.path)
            except LayoutError as missing:
                if not args.only_present:
                    print(f'✗ {missing}')
                    problems += 1
                continue
            if source.stat().st_size != asset.bytes or sha256_of(source) != asset.sha256:
                print(f'✗ {source} differs from {asset.path}')
                problems += 1
        if problems:
            raise LayoutError(f'{problems} problems')
        print('✓ The local files match the layout byte for byte')
    finally:
        files.close()


def command_fetch_origin(args: argparse.Namespace) -> None:
    """Downloads the recordings the recitations were converted from. The layout records the
    converted files, so these cannot be checked against it: convert them, then use check."""
    target = Path(args.to)
    target.mkdir(parents=True, exist_ok=True)
    for asset in read_manifest():
        if asset.origin == '-':
            continue
        path = target / PurePosixPath(asset.path).name
        if path.exists():  # download() only names a file once all of it arrived.
            continue
        print(f'  {path.name}')
        download(asset.origin, path)
    print(f'✓ Originals in {target}. Next: quran_assets.py convert --from-dir {target} --to <folder>')


def sample_rate(ffmpeg: str, source: Path) -> int | None:
    """The first audio stream's sample rate, read with the ffprobe next to [ffmpeg]."""
    ffprobe = str(Path(ffmpeg).with_name(Path(ffmpeg).name.replace('ffmpeg', 'ffprobe')))
    result = subprocess.run([ffprobe, '-v', 'error', '-select_streams', 'a:0', '-show_entries', 'stream=sample_rate',
                             '-of', 'csv=p=0', str(source)], capture_output=True, text=True)
    return int(result.stdout.strip()) if result.returncode == 0 and result.stdout.strip().isdigit() else None


def convert_recording(ffmpeg: str, source: Path, target: Path) -> None:
    """Writes [source] to [target] as AUDIO_KBPS mono MP3 at a constant bitrate, with no tags or cover art.

    One ffmpeg gives the same bytes every time; another version may not, so keep the converted
    files: the layout records them, not the originals.
    """
    partial = target.with_name(target.name + '.part')
    if is_recitation_format(source):  # Already converted: a second encoding would only lose quality.
        shutil.copyfile(source, partial)
    else:
        # MPEG-1 Layer III only exists at 32, 44.1 and 48 kHz; a lower rate would give an MPEG-2 file.
        resample = [] if sample_rate(ffmpeg, source) in (32000, 44100, 48000) else ['-ar', '44100']
        command = [ffmpeg, '-nostdin', '-hide_banner', '-loglevel', 'error', '-y', '-i', str(source),
                   '-map', '0:a:0', '-map_metadata', '-1', '-ac', '1', *resample, '-c:a', 'libmp3lame', '-b:a', f'{AUDIO_KBPS}k',
                   '-id3v2_version', '0', '-fflags', '+bitexact', '-flags:a', '+bitexact', '-f', 'mp3', str(partial)]
        result = subprocess.run(command, capture_output=True, text=True, errors='replace')
        if result.returncode != 0:
            partial.unlink(missing_ok=True)
            raise LayoutError(f'ffmpeg could not convert {source}: {result.stderr.strip()[-500:]}')
    if not is_recitation_format(partial):
        partial.unlink()
        raise LayoutError(f'Converting {source} did not give {AUDIO_KBPS} kbps mono MP3')
    partial.replace(target)


def command_convert(args: argparse.Namespace) -> None:
    ffmpeg = shutil.which('ffmpeg')
    if not ffmpeg:
        raise LayoutError('convert needs ffmpeg on the PATH. On Windows: winget install Gyan.FFmpeg, then open a new terminal')
    target = Path(args.to)
    files = LocalFiles([Path(p) for p in args.from_dir])
    try:
        mp3s = {name: paths for name, paths in files.by_name.items() if name.lower().endswith('.mp3')}
        if not mp3s:
            raise LayoutError('No MP3 files in ' + ', '.join(args.from_dir))
        if any(len(paths) > 1 for paths in mp3s.values()):
            raise LayoutError('Several recordings share a file name: convert one reciter at a time')
        recordings = sorted((name, paths[0]) for name, paths in mp3s.items())
        target.mkdir(parents=True, exist_ok=True)
        if any((target / name).resolve() == path.resolve() for name, path in recordings):
            raise LayoutError('--to must be another folder: converting in place would overwrite the originals')
        # A file already in the target format was finished by an earlier run.
        todo = [(path, target / name) for name, path in recordings
                if not ((target / name).exists() and is_recitation_format(target / name))]
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
            done = {pool.submit(convert_recording, ffmpeg, source, out): (source, out) for source, out in todo}
            for future in concurrent.futures.as_completed(done):
                future.result()
                source, out = done[future]
                print(f'  {out.name}: {source.stat().st_size / MB:.1f} MB → {out.stat().st_size / MB:.1f} MB')
        before = sum(path.stat().st_size for _, path in recordings)
        after = sum((target / name).stat().st_size for name, _ in recordings)
        print(f'✓ {len(recordings)} recordings in {target}: {before / MB:.0f} MB → {after / MB:.0f} MB')
    finally:
        files.close()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest='command', required=True)

    convert = commands.add_parser('convert', help=f're-encode recordings as {AUDIO_KBPS} kbps mono MP3 (needs ffmpeg)')
    convert.add_argument('--from-dir', action='append', required=True, help='folder or zip of original MP3s (repeatable)')
    convert.add_argument('--to', required=True, help='folder for the converted MP3s; keep it, layout reads it')
    convert.add_argument('--jobs', type=int, default=os.cpu_count() or 1, help='recordings converted at once')
    convert.set_defaults(run=command_convert)

    layout = commands.add_parser('layout', help='hash media, group packs, build zips, write the layout')
    layout.add_argument('--from-dir', action='append', required=True,
                        help='folder or zip holding the MP3s or page scans (repeatable)')
    layout.add_argument('--cdn', required=True, help='base URL of the quran-cdn Worker')
    layout.add_argument('--target-mb', type=float, default=TARGET_PACK_BYTES / MB,
                        help='pack size for reciters only the Worker serves')
    layout.set_defaults(run=command_layout)

    publish = commands.add_parser('publish', help='upload pack zips the CDN does not serve yet')
    publish.add_argument('--bucket', default='tunisian-quran-assets')
    publish.add_argument('--force', action='store_true', help='upload even if the CDN already serves the key')
    publish.set_defaults(run=command_publish)

    stage = commands.add_parser('stage', help='put Play pack files where bundleRelease packages them')
    stage.add_argument('--cache', default=str(DEFAULT_CACHE))
    stage.add_argument('--no-cache', action='store_true', help='delete each archive after extracting it')
    stage.add_argument('--from-dir', action='append', help='use local folders or zips instead of the CDN')
    stage.add_argument('--packs', nargs='*', help='only these packs')
    stage.set_defaults(run=command_stage)

    check = commands.add_parser('check', help='compare local media with the layout')
    check.add_argument('--from-dir', action='append', required=True)
    check.add_argument('--only-present', action='store_true', help='ignore layout files the folders lack')
    check.set_defaults(run=command_check)

    fetch = commands.add_parser('fetch-origin', help='download the recordings the recitations were converted from')
    fetch.add_argument('--to', required=True)
    fetch.set_defaults(run=command_fetch_origin)

    # Windows consoles may not encode ✓ and ✗; print a substitute rather than fail after the work is done.
    for stream in (sys.stdout, sys.stderr):
        if stream is not None and hasattr(stream, 'reconfigure'):
            stream.reconfigure(errors='backslashreplace')
    args = parser.parse_args(argv)
    try:
        args.run(args)
    except (LayoutError, OSError) as error:
        print(f'✗ {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
