package com.tunisianprayertimes.ui

/**
 * Hardcoded Arabic strings — replaces Android string resources for multiplatform.
 * All strings are in Arabic as per the original app.
 */
object Strings {
    const val APP_NAME = "أوقات الصلاة تونس"
    const val SUBTITLE = "مواقيت الصلاة في تونس"
    const val SOURCE = "المصدر: المعهد الوطني للرصد الجوي"
    const val STATUS_NORMAL = "الهاتف في الوضع العادي 🔔"
    const val STATUS_SILENT = "الهاتف في الوضع الصامت 🔇"
    const val STATUS_NO_PERMISSION = "يجب منح إذن عدم الإزعاج ⚠\uFE0F"
    const val BTN_SILENCE = "تفعيل الصامت 🔇"
    const val BTN_UNSILENCE = "إلغاء الصامت 🔔"
    const val INFO_TEXT = "يقوم هذا التطبيق بتفعيل وضع عدم الإزعاج تلقائيًا عند دخول وقت كل صلاة."
    const val TOAST_SILENT_ENABLED = "تم تفعيل الوضع الصامت 🔇"
    const val TOAST_NORMAL_RESTORED = "تم إيقاف الوضع الصامت 🔔"
    const val TOAST_DND_PERMISSION = "يرجى منح إذن عدم الإزعاج لهذا التطبيق"
    const val TOAST_AUTO_ENABLED = "تم تفعيل الإسكات التلقائي ✅"
    const val TOAST_AUTO_DISABLED = "تم إيقاف الإسكات التلقائي"
    const val AUTO_SILENCE = "الإسكات التلقائي أثناء الصلاة"
    const val MANUAL_SILENCE_TITLE = "الإسكات اليدوي"
    const val MANUAL_SILENCE_SUBTITLE = "اختر ما إذا كان الصامت يستمر حتى توقفه بنفسك أو لمدة محددة."
    const val MANUAL_SILENCE_MODE_UNTIL = "حتى أقوم بإيقافه"
    const val MANUAL_SILENCE_MODE_DURATION = "لمدة محددة"
    const val MANUAL_SILENCE_DURATION_LABEL = "المدة"
    const val MANUAL_SILENCE_HOURS_LABEL = "ساعة"
    const val MANUAL_SILENCE_MINUTES_LABEL = "دقيقة"
    const val MANUAL_SILENCE_ACTIVE_UNTIL_MANUAL = "سيبقى الصامت مفعّلًا حتى تقوم بإلغائه."
    const val PRAYER_SETTINGS_TITLE = "إعدادات الإسكات"
    const val PRAYER_SETTINGS_SUBTITLE = "حدد تأخير بدء الإسكات ومدته لكل صلاة. اضغط على \"د\" للتبديل إلى وقت محدد."
    const val COL_PRAYER = "الصلاة"
    const val COL_TIME = "الوقت"
    const val COL_DELAY = "التأخير"
    const val COL_DURATION = "المدة"
    const val LABEL_DELAY_MINUTES = "د"
    const val LABEL_DELAY_AT = "من"
    const val LABEL_DURATION = "د"
    const val LABEL_FIXED_TIME = "حتى"
    const val PICK_DELAY_TIME = "اختر وقت بدء الإسكات"
    const val PICK_END_TIME = "اختر وقت الانتهاء"
    const val PICK_JOMOAA_TIME = "اختر وقت صلاة الجمعة"
    const val RAMADAN_ACTIVE = "رمضان — إسكات العشاء ممتد إلى ساعة ونصف 🌙"
    const val LOCATION_TITLE = "الموقع"
    const val HINT_SEARCH_DELEGATION = "ابحث عن معتمدية…"
    const val GPS_AUTO_DETECT = "تحديد الموقع تلقائيًا 📍"
    const val PRAYER_FAJR = "الفجر"
    const val PRAYER_DHUHR = "الظهر"
    const val PRAYER_ASR = "العصر"
    const val PRAYER_MAGHRIB = "المغرب"
    const val PRAYER_ISHA = "العشاء"
    const val PRAYER_JOMOAA = "الجمعة"
    const val PRAYER_AID_FITR = "عيد الفطر"
    const val PRAYER_AID_ADHA = "عيد الأضحى"
    const val WARNING_OVERLAPS_NEXT_PRAYER = "⚠ مدة الإسكات تتجاوز وقت الصلاة التالية"
    const val ERROR_START_AFTER_END = "وقت البدء يجب أن يكون قبل وقت الانتهاء"
    const val ERROR_START_BEFORE_ATHAN = "وقت البدء يجب أن لا يكون قبل وقت الأذان"
    const val ERROR_END_BEFORE_ATHAN = "وقت الانتهاء يجب أن لا يكون قبل وقت الأذان"
    const val ERROR_OVERLAPS_NEXT_PRAYER = "وقت الانتهاء يجب أن لا يتجاوز وقت الصلاة التالية"
    const val ERROR_MANUAL_DURATION_REQUIRED = "حدد مدة صحيحة للإسكات اليدوي"
    const val DATE_TODAY = "اليوم"
    const val DATE_GO_BACK_TODAY = "العودة لليوم"
    const val NO_PRAYER_DATA = "لا تتوفر بيانات لهذا اليوم"
    const val NO_RESULTS = "لا توجد نتائج"

    // Time picker
    const val TIME_PICKER_TITLE = "اختر الوقت"
    const val CONFIRM = "تأكيد"
    const val CANCEL = "إلغاء"

    // System tray
    const val TRAY_SHOW = "إظهار النافذة"
    const val TRAY_QUIT = "خروج"
    const val TRAY_MINIMIZED = "التطبيق يعمل في الخلفية"

    fun btnSilenceForDuration(duration: String) = "تفعيل الصامت لمدة $duration 🔇"
    fun toastSilentEnabledTimed(duration: String) = "تم تفعيل الوضع الصامت لمدة $duration 🔇"
    fun manualSilenceActiveUntilTime(time: String) = "سيتم إلغاء الصامت تلقائيًا عند $time."
    fun manualSilenceSelectedDuration(duration: String) = "سيتم إلغاء الصامت تلقائيًا بعد $duration."
}
